# Copyright 2018, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: cpp

sudo: required

services:
  - docker

os:
  - linux

env:
  global:
    - V8_VERSION_LABEL=-wilton

before_install:
  - set -e
  - export V8_GIT_TAG=`git describe --exact-match --tags HEAD`
  - if [ -z ${V8_GIT_TAG} ] ; then exit 1 ; fi
  - export V8_IMAGE=v8-${V8_GIT_TAG}-linux64
  - export D="docker exec builder"
  - docker pull centos:6
  - docker run
            -id
            --name builder
            -w /opt
            -v `pwd`:/host
            -e PERL5LIB=/opt/rh/devtoolset-6/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-6/root/usr/lib/perl5:/opt/rh/devtoolset-6/root//usr/share/perl5/vendor_perl
            -e LD_LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/opt/rh/python27/root/usr/lib64
            -e PYTHONPATH=/opt/rh/devtoolset-6/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-6/root/usr/lib/python2.6/site-packages
            -e PKG_CONFIG_PATH=/opt/rh/python27/root/usr/lib64/pkgconfig
            -e PATH=/opt/rh/rh-git29/root/usr/bin:/opt/rh/python27/root/usr/bin:/opt/rh/devtoolset-6/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/depot_tools
            centos:6 bash

install:
  - $D yum install -y
            centos-release-scl-rh
  - $D yum install -y
            devtoolset-6
            python27
            rh-git29
            xz
            glib2-devel

before_script:
  - $D git clone https://github.com/ojdkbuild/upstream_jdk-8u.git /jdk
  - $D bash -c "cd /jdk ; git checkout ${OJDK_TAG}"

script:
  - $D git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - $D git clone --depth=1 https://github.com/wilton-iot/tools_linux_gn.git
  - $D git clone --depth=1 https://github.com/wilton-iot/tools_linux_patchelf.git
  - $D mv /opt/tools_linux_gn/gn /host/${V8_IMAGE}
  - sha256sum ${V8_IMAGE}.zip > ${V8_IMAGE}.zip.sha256

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TODO
  file:
    - ${V8_IMAGE}.zip
    - ${V8_IMAGE}.zip.sha256
  on:
    repo: wilton-iot/contrib_v8-ci
    tags: true

notifications:
  email:
    on_success: always

